# Generated by Django 5.1.6 on 2025-02-23 22:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_children_bio_alter_children_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('meal_description', models.TextField(blank=True, null=True)),
                ('meal_title', models.CharField(max_length=150)),
                ('intake_time', models.TimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='children.children')),
            ],
        ),
    ]
