# Generated by Django 5.1.6 on 2025-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='appetite_level',
            field=models.CharField(choices=[('low', 'Low Appetite'), ('normal', 'Normal Appetite'), ('high', 'High Appetite')], default='normal', max_length=10),
        ),
    ]
