# Generated by Django 5.1.6 on 2025-02-24 14:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_children_bio_alter_children_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hygiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('hygiene_activity_time', models.TimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hygiene_records', to='children.children')),
            ],
        ),
    ]
