# Generated by Django 5.1.6 on 2025-02-25 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_children_bio_alter_children_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('sad', 'Sad'), ('tired', 'Tired'), ('sleepy', 'Sleepy'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('frustrated', 'Frustrated')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='children.children')),
            ],
        ),
    ]
