# Generated by Django 5.1.6 on 2026-04-21 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_deactivated', 'User Deactivated'), ('user_activated', 'User Activated'), ('role_changed', 'Role Changed'), ('kindergarten_created', 'Kindergarten Created'), ('kindergarten_deleted', 'Kindergarten Deleted'), ('admin_attached', 'Admin Attached to Kindergarten'), ('admin_detached', 'Admin Detached from Kindergarten'), ('credentials_sent', 'Credentials Sent'), ('other', 'Other')], max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
