# Generated by Django 5.1.6 on 2025-02-24 21:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_children_bio_alter_children_name'),
        ('kindergarten', '0009_alter_teacherclass_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('activity_image', models.TextField(blank=True, null=True)),
                ('children', models.ManyToManyField(related_name='children_activities', to='children.children')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_activities', to='kindergarten.kindergartenclass')),
            ],
        ),
    ]
