# Generated by Django 5.1.6 on 2025-02-18 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KindergartenAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='kindergarten.kindergarten')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindergarten_admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
