# Generated by Django 5.1.6 on 2025-02-18 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0002_kindergartenadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergartenadmin',
            name='kindergarten',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='kindergarten.kindergarten'),
        ),
        migrations.AlterField(
            model_name='kindergartenadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kindergarten_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
