# Generated by Django 5.1.6 on 2025-02-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
