# Generated by Django 5.1.6 on 2026-04-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_token_expiry',
            new_name='password_reset_otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
