# Generated by Django 5.1.6 on 2025-02-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
