# Generated by Django 5.1.6 on 2025-02-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_children_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
